Monkeypatch paste mimeparse to gracefully handle improper Accept headers
Some browsers say Accept: * instead of */* and that would produce
ValueError: need more than 1 value to unpack.

See http://trac.pythonpaste.org/pythonpaste/ticket/330