Fix htmlsanitizer AttributeError when stripping an empty root tag
Introduced by df05037bcc195eadc5ea4af23b3a679b1506adef

Input such as:
	<blockquote>
	<p>
	</p>
	</blockquote>

Would trigger:

Module mediacore.lib.helpers:234 in clean_xhtml
>>  string = Cleaner(string, **_cleaner_settings)()
Module mediacore.lib.htmlsanitizer:209 in __call__
>>  self.clean()
Module mediacore.lib.htmlsanitizer:294 in clean
>>  getattr(self, method, print_error)()
Module mediacore.lib.htmlsanitizer:713 in strip_empty_tags
>>  dfs(self.root, strip_empty)
Module mediacore.lib.htmlsanitizer:705 in dfs
>>  func(node, i)
Module mediacore.lib.htmlsanitizer:711 in strip_empty
>>  self.disgorge_elem(node)
Module mediacore.lib.htmlsanitizer:758 in disgorge_elem
>>  raise AttributeError, "Can't disgorge root"
AttributeError: Can't disgorge root