Workaround broken redirect /admin/settings => /admin/settings/categories
map.redirect is triggers a redirect in the routes middleware, which uses
routes.util.url_for, which is broken in this context. It throws this:
	AttributeError: 'thread._local' object has no attribute 'mapper'

I'm avoiding the issue and moving on to more pressing tasks.