Fix some i18n errors on instantiation.
If forms were imported at boot-up time, evaluating the lambdas was
causing premature calls to _().

This was resulting in errors like:
	TypeError: No object (name: translator) has been registered for this thread